"""Remove email_lower column

Revision ID: 040a022d0935
Revises: 44dc788aa160
Create Date: 2025-04-05 12:32:35.665949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040a022d0935'
down_revision = '44dc788aa160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email_lower', type_='unique')
        batch_op.drop_column('email_lower')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_lower', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_email_lower', ['email_lower'])

    # ### end Alembic commands ###
