"""Test migration

Revision ID: 44dc788aa160
Revises: 
Create Date: 2025-04-05 12:17:17.520881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dc788aa160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_lower', sa.String(length=120), nullable=True))
        # Using batch_op to create the unique constraint
        batch_op.create_unique_constraint('uq_user_email_lower', ['email_lower'])




    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_lower')

    # ### end Alembic commands ###
